OHRI 998 lab date format changed to date-time format
UCSF-IGHS/openmrs-ohri-form-engine-lib pull request #40
Opened 2022-09-09 11:23 UTC by ODORA0

2022-09-14 08:06 UTC, samuelmale commented
@ODORA0 did you see the conflicts?

2022-09-14 08:22 UTC, samuelmale requested changes
Just a few minor comments

2022-09-14 08:22 UTC, samuelmale commented on package.json
> +    "webpack-dev-server": "^4.2.1"
@ODORA0 did you touch this file by mistake? Do we need these changes?

2022-09-14 08:22 UTC, samuelmale commented on src/components/inputs/date/ohri-date.component.tsx
> +      let prevValue = handler.getPreviousValue(question, encounterContext?.previousEncounter, fields);
```js
const prevValue = handler.getPreviousValue(question, encounterContext?.previousEncounter, fields);
```

2022-09-14 08:22 UTC, samuelmale commented on src/components/inputs/date/ohri-date.component.tsx
> +      let currentDateTime = new Date(question.value.value);
```js
 const currentDateTime = new Date(question.value.value);
```

2022-09-15 08:54 UTC, ODORA0 commented
Duplicate of https://github.com/UCSF-IGHS/openmrs-ohri-form-engine-lib/pull/43

2022-09-15 08:54 UTC, closed without merging